[package]
name = "ipfs-embed-cli"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
env_logger = "0.7.1"
exitfailure = "0.5.1"
ipfs-embed = { path = ".." }
libipld = { version = "0.3.0", features = ["dag-cbor", "dag-json", "dag-pb"] }
