[workspace]
members = ["net", "sqlite"]

[package]
name = "ipfs-embed"
version = "0.9.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[features]
default = ["db", "net"]
#db = ["ipfs-embed-db", "sled"]
db = ["ipfs-embed-sqlite"]
net = ["ipfs-embed-net"]

[dependencies]
async-global-executor = "2.0.1"
async-trait = "0.1.42"
fnv = "1.0.7"
futures = "0.3.8"
#ipfs-embed-db = { version = "0.9.0", path = "db", optional = true }
ipfs-embed-net = { version = "0.9.0", path = "net", optional = true }
ipfs-embed-sqlite = { version = "0.9.0", path = "sqlite", optional = true }
libipld = { version = "0.9.0", default-features = false }
tracing = "0.1.22"

[dev-dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
libipld = { version = "0.9.0", default-features = false, features = ["dag-cbor", "derive"] }
multihash = { version = "0.13.2", default-features = false, features = ["blake3"] }
sled = "0.34.6"
tracing-subscriber = "0.2.15"

[profile.release]
debug = true

[[bench]]
name = "list"
harness = false

[patch.crates-io]
libp2p = { path = "../rust-libp2p" }
libp2p-bitswap = { path = "../libp2p-bitswap" }
