[workspace]
members = ["bin"]

[package]
name = "ipfs-embed"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[dependencies]
async-std = { version = "=1.5.0", features = ["attributes"] }
libipld = { version = "0.3.0", default-features = false }
libp2p-bitswap = "0.4.1"
log = "0.4.8"
sled = "0.32.0-rc1"
thiserror = "1.0.19"

[dependencies.libp2p]
version = "0.19.1"
default-features = false
features = ["identify", "kad", "mdns", "mplex", "ping", "secio", "tcp-async-std", "yamux"]

[dev-dependencies]
async-log = "2.0.0"
criterion = "0.3.2"
env_logger = "0.7.1"
futures = "0.3.5"
ipld-block-builder = { version = "0.3.0", features = ["crypto"] }
ipld-collections = "0.1.1"
libipld = "0.3.0"
model = "0.1.2"
tempdir = "0.3.7"

[profile.release]
debug = true

[[bench]]
name = "list"
harness = false
