[workspace]
members = [".", "cli", "harness"]

[package]
name = "ipfs-embed"
version = "0.19.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[features]
telemetry = ["tide"]

[dependencies]
anyhow = "1.0.40"
async-global-executor = "2.0.2"
async-io = "1.3.1"
async-trait = "0.1.48"
fnv = "1.0.7"
futures = "0.3.14"
ipfs-sqlite-block-store = "0.3.0"
lazy_static = "1.4.0"
libipld = { version = "0.11.0", default-features = false }
libp2p-bitswap = "0.16.0"
libp2p-broadcast = "0.2.0"
libp2p-quic = { git = "https://github.com/ipfs-rust/libp2p-quic" }
names = "0.11.0"
parking_lot = "0.11.1"
prometheus = "0.12.0"
secrecy = "0.7.0"
thiserror = "1.0.24"
tide = { version = "0.16.0", optional = true }
tracing = "0.1.25"
void = "1.0.2"

[dependencies.libp2p]
version = "0.37.0"
default-features = false
features = [
    "dns-async-std",
    "gossipsub",
    "identify",
    "kad",
    "mdns",
    "ping",
    #"relay",
    "mplex", "noise", "pnet", "tcp-async-io", "yamux",
]
git = "https://github.com/libp2p/rust-libp2p"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
libipld = { version = "0.11.0", default-features = false, features = ["dag-cbor", "dag-pb", "derive"] }
libp2p-bitswap = { version = "0.16.0", default-features = false, features = ["compat"] }
multihash = { version = "0.13.2", default-features = false, features = ["blake3"] }
rand = "0.8.3"
tracing-subscriber = "0.2.17"

[profile.release]
debug = true

[patch.crates-io]
libp2p-bitswap = { git = "https://github.com/ipfs-rust/libp2p-bitswap" }
libp2p-broadcast = { git = "https://github.com/ipfs-rust/libp2p-broadcast" }
