[workspace]
members = [".", "cli", "harness"]

[package]
name = "ipfs-embed"
version = "0.19.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "small embeddable ipfs implementation"
repository = "https://github.com/ipfs-rust/ipfs-embed"

[features]
telemetry = ["tide"]

[dependencies]
anyhow = "1.0.40"
async-global-executor = "2.0.2"
async-io = "1.3.1"
async-trait = "0.1.48"
fnv = "1.0.7"
futures = "0.3.13"
ip_network = "0.3.4"
ipfs-sqlite-block-store = "0.3.0"
lazy_static = "1.4.0"
libipld = { version = "0.11.0", default-features = false }
libp2p-bitswap = "0.16.0"
libp2p-broadcast = "0.2.0"
names = "0.11.0"
parking_lot = "0.11.1"
prometheus = "0.12.0"
thiserror = "1.0.24"
tide = { version = "0.16.0", optional = true }
tracing = "0.1.25"
void = "1.0.2"

[dependencies.libp2p]
version = "0.36.0"
default-features = false
features = [
    # "deflate",
    "dns-async-std",
    "gossipsub",
    "identify",
    "kad",
    "mdns",
    "ping",
    "pnet",
    # "quic",
    "relay",
    "mplex", "noise", "tcp-async-io", "yamux",
]

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
libipld = { version = "0.11.0", default-features = false, features = ["dag-cbor", "dag-pb", "derive"] }
libp2p-bitswap = { version = "0.16.0", default-features = false, features = ["compat"] }
multihash = { version = "0.13.2", default-features = false, features = ["blake3"] }
rand = "0.8.3"
tracing-subscriber = "0.2.17"

[profile.release]
debug = true

[patch.crates-io]
libp2p = { path = "../rust-libp2p" }
libp2p-bitswap = { path = "../libp2p-bitswap" }
